# Generated by Django 3.2.6 on 2021-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_auto_20210825_1547'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluna',
            name='Aulas',
        ),
        migrations.AddField(
            model_name='aluna',
            name='Matriculas',
            field=models.ManyToManyField(blank=True, to='aulas.Matricula'),
        ),
    ]
