# Generated by Django 3.2.6 on 2021-08-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('Duracao', models.TimeField(blank=True, null=True)),
                ('Quantidade_Maxima_De_Alunas', models.IntegerField(blank=True, null=True)),
                ('Aula_Filmada', models.BooleanField(default=False)),
                ('Disponibilizacao_De_Equipamentos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dia_De_Aula_Disponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(blank=True, null=True)),
                ('Dia_Semana', models.CharField(blank=True, choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=255, null=True)),
                ('Inicio', models.TimeField(blank=True, null=True)),
                ('Fim', models.TimeField(blank=True, null=True)),
                ('Quantidade_Maxima_De_Alunas', models.IntegerField(blank=True, null=True)),
                ('Quantidade_Atual_De_Alunas', models.IntegerField(blank=True, null=True)),
                ('Aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.aula')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='Nivel',
            field=models.ManyToManyField(blank=True, to='aulas.Nivel'),
        ),
    ]
