# Generated by Django 3.1.1 on 2021-09-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('Duracao', models.TimeField(blank=True, null=True)),
                ('Quantidade_Maxima_De_Alunas', models.IntegerField(blank=True, null=True)),
                ('Aula_Filmada', models.BooleanField(default=False)),
                ('Disponibilizacao_De_Equipamentos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dia_De_Aula_Disponivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(blank=True, null=True)),
                ('Dia_Semana', models.CharField(blank=True, choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=255, null=True)),
                ('Inicio', models.TimeField(blank=True, null=True)),
                ('Fim', models.TimeField(blank=True, null=True)),
                ('Quantidade_Maxima_De_Alunas', models.IntegerField(blank=True, null=True)),
                ('Quantidade_Atual_De_Alunas', models.IntegerField(default=0)),
                ('Aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('Valor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.CharField(blank=True, max_length=255, null=True)),
                ('Termos_E_Condicoes', models.BooleanField(default=False)),
                ('Status', models.CharField(blank=True, choices=[('atrasado', 'Atrasado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], max_length=255, null=True)),
                ('Dia_Semana', models.CharField(blank=True, choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=255, null=True)),
                ('Inicio', models.TimeField(blank=True, null=True)),
                ('Aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.aula')),
                ('Dia_De_Aula_Disponivel', models.ManyToManyField(blank=True, to='aulas.Dia_De_Aula_Disponivel')),
                ('Frequencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.frequencia')),
                ('Nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.nivel')),
            ],
        ),
        migrations.AddField(
            model_name='dia_de_aula_disponivel',
            name='Nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.nivel'),
        ),
        migrations.AddField(
            model_name='aula',
            name='Nivel',
            field=models.ManyToManyField(blank=True, to='aulas.Nivel'),
        ),
    ]
