# Generated by Django 3.2.6 on 2021-08-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='Valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.CharField(blank=True, max_length=255, null=True)),
                ('Dia_De_Aula_Disponivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.dia_de_aula_disponivel')),
                ('Frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.frequencia')),
            ],
        ),
    ]
