# Generated by Django 3.2.6 on 2021-08-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20210825_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia_de_aula_disponivel',
            name='Nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.nivel'),
        ),
        migrations.AlterField(
            model_name='dia_de_aula_disponivel',
            name='Quantidade_Atual_De_Alunas',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Dia_De_Aula_Disponivel',
        ),
        migrations.AddField(
            model_name='matricula',
            name='Dia_De_Aula_Disponivel',
            field=models.ManyToManyField(blank=True, null=True, to='aulas.Dia_De_Aula_Disponivel'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='Frequencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.frequencia'),
        ),
    ]
