# Generated by Django 3.2.6 on 2021-08-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('aulas', '0003_auto_20210825_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia_de_aula_disponivel',
            name='Alunas',
            field=models.ManyToManyField(blank=True, null=True, to='users.Aluna'),
        ),
        migrations.AddField(
            model_name='dia_de_aula_disponivel',
            name='Professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='Aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.aula'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='Horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='Status',
            field=models.CharField(blank=True, choices=[('atrasado', 'Atrasado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='Termos_E_Condicoes',
            field=models.BooleanField(default=False),
        ),
    ]
