# Generated by Django 3.2.6 on 2021-08-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210825_1547'),
        ('aulas', '0004_auto_20210825_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='Aluna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.aluna'),
        ),
    ]
