# Generated by Django 3.2.6 on 2021-08-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210825_1547'),
        ('aulas', '0005_matricula_aluna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='Horario',
        ),
        migrations.AddField(
            model_name='matricula',
            name='Fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='Inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dia_de_aula_disponivel',
            name='Alunas',
            field=models.ManyToManyField(blank=True, to='users.Aluna'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='Dia_De_Aula_Disponivel',
            field=models.ManyToManyField(blank=True, to='aulas.Dia_De_Aula_Disponivel'),
        ),
    ]
