# Generated by Django 3.2.6 on 2021-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0006_auto_20210825_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='Dia_Semana',
            field=models.CharField(blank=True, choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=255, null=True),
        ),
    ]
