# Generated by Django 3.2.6 on 2021-08-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0007_matricula_dia_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='Dia_Semana',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Fim',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Inicio',
        ),
        migrations.AddField(
            model_name='matricula',
            name='Nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.nivel'),
        ),
    ]
